// AUTH
export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";

// CASH
export const GET_CASH_HISTORIES = "GET_CASH_HISTORIES";
export const REGISTER_CASH_AMOUNT = "REGISTER_CASH_AMOUNT";
export const CONFIRM_CASH_AMOUNT = "CONFIRM_CASH_AMOUNT";
export const EDIT_CASH_AMOUNT = " EDIT_CASH_AMOUNT";
export const DELETE_CASH = "DELETE_CASH";

// PRODUCTS
export const REGISTER_PRODUCT = "REGISTER_PRODUCT";
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const CHANGE_STATUS = "CHANGE_STATUS";
export const CHANGE_DISCOUNT = "CHANGE_DISCOUNT";
export const DELETE_PRODUCT = " DELETE_PRODUCT";
export const GET_PRODUCT_BY_SEARCH = "GET_PRODUCT_BY_SEARCH";

// LOADING
export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";
